server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chency821/microservicecloud-config.git  #github上git的仓库地址
